### ISSUE TITLE
Example for application within a bounded context 

### ISSUE THREAD

**Issue by sunilk-m** [ContextMapper/contextmapper.github.io#49]
Is there any example for Application rule defined within a bounded context. I wanted to use flow to define a 
command 'CommandEvent' delegates to 'Aggregate' emits event 'DomainEvent'

Regards
Sunil

**Comment by stefan-ka** [comment]
Hi @sunilk-m 

Nice to hear that you use @ContextMapper and that you analyze our Xtext grammar :)
Unfortunately, the application rule and the application flow feature is not yet released... We are working on this, but it is not part of an official @ContextMapper release. Therefore, the answer for now is no, we have not yet documented this feature.

I can let you know as soon as we have a release that contains this new feature.

Best regards,
Stefan

PS: The following screenshot might give you an idea on how we think that this shall work in the future :)

![image](https://user-images.githubusercontent.com/6763278/99963447-1a9e7700-2d92-11eb-81cf-c8cbaa9e2c7a.png)

**Comment by sunilk-m** [comment]
Hi Stefan
Thanks for your prompt reply. We started using it a week back primary
to build a tool for generating code and all of us are impressed by it. I
had used xtext earlier so it was easier for me to learn by looking at the
grammar :).

Regards
Sunil

**Comment by stefan-ka** [comment]
Cool, @sunilk-m! :)

We are always happy to hear how @ContextMapper is applied in projects and what requirements you may have. So, feel free to share your experience (you can also reach me via other channels: https://stefan.kapferer.ch/about/), create issues on GitHub, or even create PRs. Input and feedback is very welcome!

Best regards,
Stefan

**Comment by socadk** [comment]
Hi there, Context Mapper 6.2 and 6.3 now have the doc pages for app flow modeling: https://contextmapper.org/docs/application-and-process-layer/

**Comment by stefan-ka** [comment]
Yes, thanks @socadk! 

I guess this issue is fixed @sunilk-m, right? (I know you already saw the new features/releases :)
A few example models can also be found here: https://github.com/ContextMapper/context-mapper-examples/tree/master/src/main/cml/workflow-samples

I close this one. If you need more help, let us know @sunilk-m.
