### ISSUE TITLE
IntelliJ plug-in?

### ISSUE THREAD

**Issue by xenoterracide** [ContextMapper/contextmapper.github.io#64]
Is one of these going to be written? Probably this is an faq question.

**Comment by stefan-ka** [comment]
Yes, this question is already asked a few times :)

https://github.com/ContextMapper/context-mapper-dsl/issues/173

The unfortunate thing is that IntelliJ is not supporting [lsp](https://microsoft.github.io/language-server-protocol/), which would make our existing code re-usable. We will have to implement everything from scratch for IntelliJ (at least the editor-features).
I hope I will find that time once :)

**Comment by stefan-ka** [comment]
I will close this one, as we already have it here: https://github.com/ContextMapper/context-mapper-dsl/issues/173
