### ISSUE TITLE
Dead link on landing page

### ISSUE THREAD

**Issue by hwanders** [ContextMapper/contextmapper.github.io#70]
The first bullet point on the landing page contains a link to the project's background using the URL `/docs/background-and-publications/`.

> [What is Context Mapper?](https://contextmapper.org/docs/home/) Learn more about the [project's background](https://contextmapper.org/docs/background-and-publications/).

Unfortunately, that page does not exist.
You probably wanted to link to `/background-and-publications/`.

**Comment by stefan-ka** [comment]
Hi @hwanders 

Thank you very much for reporting it! I fixed it now...

Best regards,
Stefan
