### ISSUE TITLE
partnership and shared-kernel dont explain what they are

### ISSUE THREAD

**Issue by SkinyMonkey** [ContextMapper/contextmapper.github.io#73]
In those pages:

https://contextmapper.org/docs/partnership/
https://contextmapper.org/docs/shared-kernel

There is no explanation about what a partnership relationship is or what a shared-kernel relationship is.

**Comment by stefan-ka** [comment]
Thanks for reporting @SkinyMonkey!

Actually I don't think we should explain all the DDD patterns here again, because there is enough literature about it. But you are right, we could at least make some links/references :+1:

**Comment by socadk** [comment]
Hi @SkinyMonkey would a short excerpt from the description of Strategic DDD and the relationship patterns in the [Design Practice Repository/Reference](https://leanpub.com/dpr) help? https://socadk.github.io/design-practice-repository/activities/DPR-StrategicDDD.html 

@stefan-ka The DPR repo is under CC BY 4.0 (just FYI)

**Comment by SkinyMonkey** [comment]
I think that the second link you posted is better suited.
An excerpt might lack context.

Thank you for checking this!

**Comment by socadk** [comment]
We updated the Language Semantics page https://contextmapper.org/docs/language-model/ and added links to this page on the pages for partnership and shared-kernel.
