### ISSUE TITLE
Graphical Context Map generation not working on eclipse 2023-03

### ISSUE THREAD

**Issue by ivanfernandezetu** [ContextMapper/contextmapper.github.io#89]
Hi,

I'm having issues to generate context maps with eclipse 2023-03 (tried various packages) and MacOS Monterrey. Graphviz is installed and added to the path as displayed in the eclipse terminal window on the screenshot below:

<img width="948" alt="image" src="https://github.com/ContextMapper/contextmapper.github.io/assets/26252235/45868906-2ece-42b3-9278-bee0ffdaa3be">

Any idea of what could be going wrong?

Thanks

**Comment by stefan-ka** [comment]
Hi @ivanfernandezetu 

We already had an issue on MacOS once: https://github.com/ContextMapper/context-mapper-dsl/issues/199
There is a link in that issue (stackoverflow) that solved it for most Mac users at that time.

Could you check whether that is still a valid solution?

Thanks and best regards,
Stefan

**Comment by ivanfernandezetu** [comment]
Hi @stefan-ka 

Thanks for your quick response.

Creating an environment.plist file in ~/Library/LaunchAgents/ worked for me.

Thanks a mill. Regards
